### PR TITLE
hw 9 improved

### PR DESCRIPTION
**Pull request by noynoy55**

### CODE REVIEW

**Comment by noynoy55** [comment]
hope this works

**Comment by melvyniandrag** [comment]
Doesn't work. Something has gone very wrong with your git setup! You've sent me a submodule, which is an advanced thing that I don't want to use. We'll have to look at your laptop in class to see what has happened! git is really difficult to use, it's very good that you get all these errors so you learn about it.

**Comment by melvyniandrag** [comment]
You can delete your fork, create a new fork, and make a pull request with that in the mean time.

**Comment by noynoy55** [comment]
Hopefully some day. …..)

**Pull request closed without merging**
