### PR TITLE
pushing backend

### PR DESCRIPTION
**Pull request by popcor255**

### CODE REVIEW

**Comment by popcor255** [comment]
lag

**Comment by melvyniandrag** [comment]
57000 files in here chief youve done something terribly wrong

**Comment by popcor255** [comment]
Not really. I pushed the source code with my source files. I can send you the build files, but it wont do much good. Ill remove the node_modules, I think that is what your talking about. Ill add a git ignore to my push.

**Comment by melvyniandrag** [comment]
I saw the first few files were .profile .bashrc etc i didnt scroll through everything but I figured you just pushed your whole home directory.

Anyway, petition to change sedjedi to 'sedi'

**Comment by popcor255** [comment]
I opened a new pr, ill make the changes over there.

**Pull request closed without merging**
