### PR TITLE
Homework11

### PR DESCRIPTION
**Pull request by bryannn716**

### CODE REVIEW

**Comment by melvyniandrag** [comment]
the image is not correct!  There is no 'uptime', etc. Read the homework carefully.

**Comment by bryannn716** [comment]
the homework states to run the command 'uptime'. The command is ran as soon as I logged back on along with 'lsblk' and cat /etc/fstab/

**Comment by melvyniandrag** [comment]
I'll check again sorry for the mistake the image I saw didnt show that, maybe it was cropped, I was using the web viewer and didn't actually download the files

**Comment by melvyniandrag** [comment]
I'll check again sorry for the mistake the image I saw didnt show that, maybe it was cropped, I was using the web viewer and didn't actually download the files

**Pull request merged**
